project:
  type: website

website:
  title: "PRIYANGA DILINI TALAGALA"
  navbar:
    background: "#000000"  # Example color, replace with your desired color
    foreground: "#ffffff"  # Example color, replace with your desired color
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
     # - text: "License"
      #  href: license.qmd
    #  - text: "Trademark"
     #   href: trademark.qmd
    background: "#000000"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

