project:
  type: website

website:
  title: "PRIYANGA DILINI TALAGALA"
  
  favicon: "/images/icon-32.png"
  twitter-card:
    image: "/images/DSC_0543.png"
  open-graph:
    image: "/images/DSC_0543.png"
    
    
  navbar:
    background: "#000000"  # Example color, replace with your desired color
    foreground: "#ffffff"  # Example color, replace with your desired color
    left:
      - href: about.qmd
        text: About
      - href: talks.qmd
        text: Talks
      - href: https://scholar.google.com.au/citations?user=r4PXCAsAAAAJ&hl=en
        text: Publications
      - href: courses.qmd
        text: Teaching
    right:
      - icon: twitter
        href: https://twitter.com/pridiltal
      - icon: github
        href: https://github.com/pridiltal
      - icon: linkedin
        href: "https://www.linkedin.com/in/priyanga-dilini-talagala-47b269122/"
      - icon: google-scholar
        text: Google Scholar
        href: https://scholar.google.com.au/citations?user=r4PXCAsAAAAJ&hl=en
      - icon: orcid
        text: ORCID
        href: "http://orcid.org/0000-0003-2870-7449"
        
  page-footer:
    center:  &copy; Copyright 2017 - 2024 Priyanga Dilini Talagala. Powered by [Quarto](https://quarto.org/).
    background: "#000000"
    
    right:
      - icon: twitter
        href: https://twitter.com/pridiltal
      - icon: github
        href: https://github.com/pridiltal
      - icon: linkedin
        href: "https://www.linkedin.com/in/priyanga-dilini-talagala-47b269122/"
      - icon: google-scholar
        text: Google Scholar
        href: https://scholar.google.com.au/citations?user=r4PXCAsAAAAJ&hl=en
      - icon: orcid
        text: ORCID
        href: "http://orcid.org/0000-0003-2870-7449"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

