---
title: "Talks"
about:
  template: solana
---

# 2024

## **Exploring Class Overlap in Classification Challenges: Introducing the R Package** `clap`

**Date:** July 10, 2024 1.50 PM

Event: [useR! 2024, Salzburg, Austria](https://events.linuxfoundation.org/user/)

[Slides](https://pridiltal.github.io/useR2024-talk/#/)

## **A Backcasting Approach for Anomaly Detection in Time Series Data**

**Date:** July 01, 2024 11.00 AM

Event: [44th International Symposium on Forecasting, Dijon, France](https://isf.forecasters.org/)

[Slides](https://pridiltal.github.io/ISF2024-talk/)

## **Exploring Dynamics and Trends in Distance Education: Insights from Global Web Search Queries in the Post-Pandemic Era**

**Date**: July 05, 2024 09:00 AM

Event: [8th International Conference on Education and Distance Learning, Paris, France](https://www.icedl.org/index.html)

[Slides](https://pridiltal.github.io/ICEDL2024/index.pdf)

## **From Crisis to Opportunity: A Google Trends Analysis of Global Interest in Distance Education Tools During and Post the COVID-19 Pandemic**

**Date**: June 28, 2024 09:00 AM

Event: [6th International Conference on Advanced Research Methods and Analytics, Valencia, Spain](https://carmaconf.org/)

[Slides](https://pridiltal.github.io/CARMA2024/index.pdf)

## **The AI Revolution: Historical Footprints Current Applications and Future Landscapes**

**Date**: Mar 20, 2024 02:00 PM

Event: INTELLECTA 24, ICT Day, Devi Balika Vidyalaya, Colombo 8

[Slides](https://pridiltal.github.io/Devi_Balika_ICT_Day/#1)

# 2023

## Beyond the Abstract - A Guide to Writing Conference Research Articles

**Date:** Aug 9, 2023 12:00 AM — 12:00 AM

**Event:** Information Technology Research Unit (ITRU) Faculty of Information Technology, University of Moratuwa, Pre-conference workshop

[Sldies](https://prital23.netlify.app/talks/icitr2023/icitr2023#1)

## Forecasting and Anomaly Detection in Large-Scale Time Series

**Date:** Jan 25, 2023 12:00 AM — 12:00 AM

**Event:** F4SG Learning Labs

**Location:** F4SG Learning Labs

[Slides](https://prital23.netlify.app/talks/f4sg2023/f4sg-talk)

# 2022

## Anomaly Detection in Image Streams with Explainable AI

**Date:** May 18, 2022 12:00 AM — 12:00 AM

**Event:** OCTAVE Advanced Analytics Symposium

**Location:** Virtual Symposium

[Sldies](https://prital23.netlify.app/talks/OCTAVE2022/OCTAVE2022.pdf)

## Detecting Technical Anomalies in Water-Quality Data From River Networks

**Date:** May 10, 2022 12:00 AM — 12:00 AM

**Event:** [2022 Joint Aquatic Sciences Meeting Statistical Association](https://jasm2022.aquaticsocieties.org/)

**Location:** Grand Rapids, Michigan (Virtual Conference)

[Slides](https://prital23.netlify.app/talks/jasm2022/jasm2022)

# 2021

## Technical Anomalies in Water-Quality Data From In-Situ Sensors - What, Why, and How?

**Date:** Nov 28, 2021 12:00 AM — 12:00 AM

**Event:** [ARCLP Workshop: Revolutionising water quality monitoring in the information age](https://www.youtube.com/playlist?list=PLBxgDdQG5yHJhcro1Tovt1PIHF1u-exCe)

[Slides](https://prital23.netlify.app/talks/arclp2021/arclp2021), [Youtube](https://www.youtube.com/playlist?list=PLBxgDdQG5yHJhcro1Tovt1PIHF1u-exCe)

## Attention Towards Distance Education Tools During COVID-19 Pandemic - Evidence from Google Trends

**Date:** Nov 8, 2021 12:00 AM — Nov 19, 2021 12:00 AM

**Event:** [OWSD 6th General Assembly and International Conference](https://owsd.net/news/news-events/owsd-6th-general-assembly-and-international-conference)

**Location:** Virtual Conference

[Slides](https://prital23.netlify.app/talks/owsdga62021/owsd_talk#1)

## Anomaly Detection in Spatio-Temporal Tensor Streams

**Date:** Aug 6, 2021 12:00 AM — 12:00 AM

**Event:** [2021 Joint Statistical Meetings - American Statistical Association](https://ww2.amstat.org/meetings/jsm/2021/)

**Location:** Virtual ISF Conference 2021

[Slides](https://prital23.netlify.app/talks/jsm2021/jsm2021-talk)

## Tidy Time Series Anomaly Detection for Load Forecasting

**Date:** Jun 30, 2021 12:00 AM — 12:00 AM

**Event:** [41st International Symposium on Forecasting, Virtual Conference.](https://forecasters.org/events/symposium-on-forecasting/)

**Location:** Virtual ISF 2021 (Virtual Conference)

[Slides](https://prital23.netlify.app/talks/isf2021/isf-2021#1)

## Plot a lot with ggplot2 to find plots

**Date:** Jan 27, 2021 12:00 AM — 12:00 AM

**Event:** [R-Ladies Meetup.](https://www.meetup.com/rladies-colombo/events/275639176/)

**Location:** R-Ladies Meetup, R-Ladies Meetup

[Slides](https://prital23.netlify.app/talks/rladies2021/rladies-ggplot2)

# 2020

## Anomaly Detection in Streaming Time Series Data

**Date:** Dec 4, 2020 12:00 AM — 12:00 AM

**Event:** StatScale Seminar

**Location:** StatScale Seminar, Lancaster University, UK

[Slides](https://prital23.netlify.app/talks/statscale2020/statscale2020#1)

## Tensor-based anomaly detection in multivariate spatio-temporal data

**Date:** Oct 26, 2020 12:00 AM — Oct 28, 2020 12:00 AM

**Event:** [40th International Symposium on Forecasting, Rio de Janeiro, Brazil.](https://isf.forecasters.org/)

**Location:** Virtual ISF 2020, Rio de Janeiro, Brazil

[Slides](https://prital23.netlify.app/talks/isf2020/isf2020#1)

# 2019

## Anomaly Detection in R

**Date:** Jul 9, 2019 12:00 AM — Jul 12, 2019 12:00 AM

**Event:** [useR! 2019, Toulouse , France.](http://www.user2019.fr/)

**Location:** The congress centre - Pierre Baudis, Toulouse, France

[Slides](https://prital23.netlify.app/talks/user2019/user2019)

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

Impressive work by <a href="https://twitter.com/pridiltal?ref_src=twsrc%5Etfw">@pridiltal</a> on anomaly detection in streaming data, demonstrated on several applications: <a href="https://t.co/1nVBgHFgKX">https://t.co/1nVBgHFgKX</a> <a href="https://twitter.com/hashtag/useR2019?src=hash&amp;ref_src=twsrc%5Etfw">#useR2019</a> <a href="https://t.co/7eSv0ilf68">pic.twitter.com/7eSv0ilf68</a>

</p>

— Tim Radtke (@TimRadtke) <a href="https://twitter.com/TimRadtke/status/1148901033659293696?ref_src=twsrc%5Etfw">July 10, 2019</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

Very interesting presentations on forecasting, outliers, smoothing, features and time series in tidy formats by <a href="https://twitter.com/mitchoharawild?ref_src=twsrc%5Etfw">@mitchoharawild</a>, <a href="https://twitter.com/iSvetunkov?ref_src=twsrc%5Etfw">@iSvetunkov</a>, <a href="https://twitter.com/robjhyndman?ref_src=twsrc%5Etfw">@robjhyndman</a>, <a href="https://twitter.com/pridiltal?ref_src=twsrc%5Etfw">@pridiltal</a> and <a href="https://twitter.com/thiyangt?ref_src=twsrc%5Etfw">@thiyangt</a> at the <a href="https://twitter.com/hashtag/useR2019?src=hash&amp;ref_src=twsrc%5Etfw">#useR2019</a> <a href="https://t.co/OBAujqXEYg">pic.twitter.com/OBAujqXEYg</a>

</p>

— Fotios Petropoulos (@fotpetr) <a href="https://twitter.com/fotpetr/status/1149625367767875584?ref_src=twsrc%5Etfw">July 12, 2019</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

Great <a href="https://twitter.com/hashtag/user2019?src=hash&amp;ref_src=twsrc%5Etfw">#user2019</a> talk by <a href="https://twitter.com/pridiltal?ref_src=twsrc%5Etfw">@pridiltal</a> ????????????<br>"Anomaly detection in R"<br>Very interesting application!<br><br>I didn't realise that those slides were not beamer till the end! (the tourrr animation should have given it away)<br><br>???? <a href="https://t.co/qjmsCGhdee">https://t.co/qjmsCGhdee</a><br>???? <a href="https://t.co/0kYkTWXotD">https://t.co/0kYkTWXotD</a> <a href="https://t.co/pbfJ9nO7KA">pic.twitter.com/pbfJ9nO7KA</a>

</p>

— Emi Tanaka ???? (@statsgen) <a href="https://twitter.com/statsgen/status/1170526072812625920?ref_src=twsrc%5Etfw">September 8, 2019</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
## A feature-based framework for detecting technical outliers in water-quality data from in situ sensors

**Date:** Jun 18, 2019 12:00 AM — 12:00 AM

**Event:** [39th International Symposium on Forecasting, Thessaloniki, Greece.](https://isf.forecasters.org/)

**Location:** Makedonia Palace, Thessaloniki, Greece

[Slides](https://prital23.netlify.app/talks/isf2019/isf2019#1)

# 2018

## Outlier Detection in Non-Stationary Data Streams

**Date:** Aug 28, 2018 12:00 AM — 12:00 AM

**Event:** [Joint International Society for Clinical Biostatistics and Australian Statistical Conference 2018, Melbourne, Australia](https://iscbasc2018.com/)

**Location:** Melbourne Convention and Exhibition Centre, Australia

[Slides](https://prital23.netlify.app/talks/iscb2018/iscb2018#1)

I won EJP Pitman Young Statisticians Prize 2018, Merit Award for the outstanding talk presented by a Young Statistician at an Australian Statistical Conference

## Outlier Detection in Non-Stationary Data Streams

**Date:** Jul 31, 2018 12:00 AM — 12:00 AM

**Event:** [2018 Joint Statistical Meetings - American Statistical Association, Vancouver, Canada](http://ww2.amstat.org/meetings/jsm/2018/)

**Location:** Vancouver Convention Centre, Vancouver, British Columbia, Canada

[Sldies](https://prital23.netlify.app/talks/jsm2018/jsm2018#1)

## oddstream and stray-Anomaly Detection in Streaming Temporal Data with R

**Date:** Jul 11, 2018 12:00 AM — 12:00 AM

**Event:** [useR! 2018, Brisbane, Australia](https://forecasters.org/events/symposium-on-forecasting/)

**Location:** Brisbane Convention ad Exhibition Centre, Brisbane, Australia

[Slides](https://prital23.netlify.app/talks/user2018/user2018#1)

## Anomaly Detection in Nonstationary Streaming Temporal Data

**Date:** Jun 18, 2018 12:00 AM — 12:00 AM

**Event:** [38th International Symposium on Forecasting, Boulder, Colorado, USA](https://forecasters.org/events/symposium-on-forecasting/)

**Location:** University of Colorado (CU), Colorado, USA

[Slides](https://prital23.netlify.app/talks/isf2018/isf2018#1) , [Paper](https://www.tandfonline.com/doi/abs/10.1080/10618600.2019.1617160)

# 2017

## Detecting Anomalous Series in Streaming Time Series Data

**Date:** Sep 26, 2017 12:00 AM — 12:00 AM

**Event:** [Young Statisticians Conference 2017](http://ysc2017.com.au/)

**Location:** Tweed Events, Twin Towns 2 Wharf St, Tweed Heads NSW, Australia

[Slides](https://prital23.netlify.app/talks/ysc2017/ysc2017v2#1)

## Detection of Anomalous Series Within a Large Collection of Streaming Time Series Data

**Date:** Sep 19, 2017 12:00 AM — 12:00 AM

**Event:** [Young Stats Showcase - September 19, 2017](https://www.meetup.com/Statistical-Society-of-Australia-Victorian-Branch/events/241236189/)

**Location:** Evan Williams Theatre, Peter Hall Building, University of Melbourne, Melbourne, Australia

[Sldies](https://prital23.netlify.app/talks/youngstats2017/youngstatsshowcase17#1)

## Anomaly Detection in Streaming Time Series Data

**Date:** June 25-28, 2017

**Event:** [37th International Symposium on Forecasting, Cairns, Australia](https://forecasters.org/isf/)

**Location:** Cairns Convention Centre, Cairns, Australia

[Slides](https://prital23.netlify.app/talks/isf2017/isf2017ninjav6#1)
